#!/bin/bash

clear
echo -e "\033[36m"
echo "    _____            _                ____                       "
echo "   |_   _|   _ _ __ (_)_ __   __ _   / ___| __ _ _ __ ___   ___  "
echo "     | || | | | '_ \| | '_ \ / _  | | |  _ / _  | '_   _ \ / _ \ "
echo "     | || |_| | |_) | | | | | (_| | | |_| | (_| | | | | | |  __/ "
echo "     |_| \__, | .__/|_|_| |_|\__, |  \____|\__,_|_| |_| |_|\___| "
echo "         |___/|_|            |___/                               "

echo -e "\n \n"
echo -e "\tWelcome in FastTyping, made by maegaspa\n"

read -p "Choose 30 or 60 seconds : " reponse

if [ "$reponse" = "30" ]
then 
    clear
    read -p "Press 0 to start the game : " press
    fin=`date +"%s"`
    let fin=$fin+30
    i=0
    while [ "$press" = "0" ]
    do
        echo -e '\n'
        echo -e "\t           GO"
        while [ `date +"%s"` -lt $fin ]
        do
            if : 
            then
                variable=$(python -c "import random, sys; print random.choice(open('./wordbank').readlines());" < ~/init/scripts/wordbank)
                printf "$variable\n"
                read -p $'' bite
                if [ "$bite" == "$variable" ]
                then
                    i=$(($i + 1))
                    clear
                fi
            fi
        done
        clear
        press=1
    done
    i=$(($i * 2))
    echo -e "Game Over, your score is $i words per minute.\n\n\n\n"
    read -p "Would you like to play again ? [y/n] : " again
    if [ "$again" = "y" ]
    then
        exec "$0"
    fi
	if [ "$again" = "n" ]
	then
		exit 0
	fi
fi

if [ "$reponse" = "60" ]
then 
    clear
    read -p "Press 0 to start the game : " press
    fin=`date +"%s"`
    let fin=$fin+30
    i=0
    while [ "$press" = "0" ]
    do
        echo -e '\n'
        echo -e "\t           GO"
        while [ `date +"%s"` -lt $fin ]
        do
            if : 
            then
                variable=$(python -c "import random, sys; print random.choice(open('./wordbank').readlines());" < ~/init/scripts/wordbank)
                printf "$variable\n"
                read -p $'' bite
                if [ "$bite" == "$variable" ]
                then
                    i=$(($i + 1))
                    clear
                fi
            fi
        done
        clear
        press=1
    done
    echo -e "Game Over, your score is $i words per minute.\n\n\n\n"
    read -p "Would you like to play again ? [y/n] : " again
    if [ "$again" = "y" ]
    then
        exec "$0"
    fi
	if [ "$again" = "n" ]
	then
		exit 0
	fi
fi
